# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import game_pb2 as game__pb2


class RockPaperScissorsStub(object):
  """Service to play a game of Rock-Paper-Scissors.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Game = channel.unary_unary(
        '/rockpaperscissors.RockPaperScissors/Game',
        request_serializer=game__pb2.GameRequest.SerializeToString,
        response_deserializer=game__pb2.GameResponse.FromString,
        )


class RockPaperScissorsServicer(object):
  """Service to play a game of Rock-Paper-Scissors.
  """

  def Game(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RockPaperScissorsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Game': grpc.unary_unary_rpc_method_handler(
          servicer.Game,
          request_deserializer=game__pb2.GameRequest.FromString,
          response_serializer=game__pb2.GameResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rockpaperscissors.RockPaperScissors', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
